### ISSUE TITLE
Missing POM in repository?

### ISSUE THREAD

**Issue by MikeKutz** [oddgen/oddgen#17]
I'm attempting to build the latest version of the oddgen plugin but I am getting a build error saying "there is no POM file in this directory".  (see image)

![missing pom](https://cloud.githubusercontent.com/assets/14933751/15092524/83aa2760-143a-11e6-9717-6b64e8c1e884.jpg)

**Comment by MikeKutz** [comment]
EBKAC error.

I needed to `cd sqldev` from the base oddgen repository.

I finally got the build to work.

(for the record) notes from my build problems
You need SQL*Developer 4.1.x.
Version 4.0.x does not have the correct JARs.

The following must work from the command line (Windows)
- `"%JAVA_HOME%/bin/javac" -version` (I'm assuming you need javac.exe, not java.exe)
- `git --version`
- `mvn -v`
- from the directory you run mvn, `dir *.pom`

Windows users
The parameter `sqldev.basedir` may need to include the drive letter.
If you are using the GitHub installation of git, read this thread to add `git.exe` to your path
http://stackoverflow.com/questions/11928561/where-is-git-exe-located

MK

**Comment by PhilippSalvisberg** [comment]
Thank you for the feedback. I'm glad to hear that you've managed to build the extension according the "How to Build" instructions in the [README.md](https://github.com/oddgen/oddgen/blob/master/README.md#how-to-build). RTFM would have saved some time I guess ;-)

> (for the record) notes from my build problems
> You need SQL*Developer 4.1.x.
> Version 4.0.x does not have the correct JARs.

SQL Developer 4.0.x comes with all necessary JAR files. However, they are located in different directories compared to SQL Developer 4.1.x. The current POM depends on 4.1.x, but it wouldn't be a problem to change the POM to work with a 4.0.x installation. This is also a reason why the resulting oddgen extension may be used in SQL Developer 4.0.x and 4.1.x.
