### ISSUE TITLE
Change method of generating GUI?

### ISSUE THREAD

**Issue by MikeKutz** [oddgen/oddgen#20]
With issue #19
I'm beginning to wonder if using raw Swing is the best method for display GUI for parameters.

From experience, building code to properly generate the GUI for a dynamic forms can be extremely complex.  Personally, I would have started with an HTML Render instead of dynamically building the form with Swing.

For this project, you would really only need to create an XSLT that allows you to take the XML (that oddgen builds) from the generator and XMLTransform() it into HTML .... or FXML (JavaFX).
(of course, you may still need to dynamically build the hooks)

My $0.02

MK

**Comment by PhilippSalvisberg** [comment]
SQL Developer is a Swing application. And there are a lot of dynamic UI elements within SQL Developer.

The oddgen extension supports just the newer SQL Developer versions, currently
- 4.0 (needs JRE7 or higher, was typically bundled with a JDK7)
- 4.1 (needs JRE8, is typically bundled with a JDK8) 

Java 7 and JavaFx? - Nah, bad idea. Just adding JavaFX to the classplath within an OSGi bundle when you do not have control over the application is a major hack. I've got it to work in another project, but the result was unstable and simply not worth the effort. 

oddgen has to integrate into SQL Developer. Therefore we have to understand the underlying concepts and technologies to use them properly.

Furthermore, fixing issue #19 was a trivial thing. Switching the UI technology, based on such a bug, would be disproportionate.
