### ISSUE TITLE
Parameter Defaults not updated in GUI until after refreshing the Generators Navigator

### ISSUE THREAD

**Issue by ssentinel** [oddgen/oddgen#21]
When the results of the Get_Params function changes over time, the generated GUI does not update to the new defaults/list of parameters.

I implemented the parameters as a package level global value (g_Param) initialized in the package bodies initialization section.  In the Get_Object_Types function I return an object type of DEFAULT in addition to other object types.  In the Get_Object_Names function I return a value of SETTINGS when the object type is DEFAULT.  In the Generate function the g_Param global value is updated to the values passed in by the in_Params parameter when the object type is DEFAULT.  However, the next time I right click->Generate... a node in the Generators Navigator the new defaults are not reflected in the GUI until after clicking the refresh button.

**Comment by PhilippSalvisberg** [comment]
That's expected behaviour. `get_params` is called when refreshing or selecting a new database connection among other settings.  The default value for a parameter is independent of an object type. If the valid values differ per object type I suggest to set the default value for these parameters to NULL, define a list of values including NULL in `get_lov`/`refresh_lov` and handle the defaults (NULLs) in `generate`.

**Comment by ssentinel** [comment]
I wasn't specifically using different defaults nor even different parameters per object type.  I was re-implementing the Dropall sample generator just to get a feel for things.  I wanted to see if I could persist the parameter list instead of regenerating it every time the get_params function was called.  A natural out growth of that was, now that it's persisted as a global package variable how about updating it's value to change the default values for future calls (for example changing the default value of Purge? from No to Yes) in my version of the Purgeall generator.

**Comment by PhilippSalvisberg** [comment]
The `get_params` function is just called once per generator and I'd like to keep it that way. I consider changing default values for a subsequent call in the same session as a corner case. In fact you may select multiple object nodes and process them together and therefore avoid/reduce subsequent calls. If you really want to persist your settings than a table is probably the better choice, but a refresh is still required to clear the cached settings.

**Comment by PhilippSalvisberg** [comment]
wil be addressed by #22
