### ISSUE TITLE
Sorting of parameters not working

### ISSUE THREAD

**Issue by ogobrecht** [oddgen/oddgen#23]
Hi Philipp,

first of all: thank you for this great project!

I have problems with the sort order and visibility of the parameters. In one of your examples I found the functions get_ordered_params and refresh_param_states. They are missing in the documentation.

I have implemented these functions, but they don't work as expected. I don't know if these functions are working in the current release 0.1.1. 

Here some details:

``` sql
SUBTYPE param_type IS VARCHAR2(100 CHAR);
```

``` sql
-- get_ordered_params returns the same order
  c_unchange_existing_api_params CONSTANT param_type := 'Unchange existing API package parameters';
  c_col_prefix_in_method_names   CONSTANT param_type := 'Keep column prefix in method names';
  c_enable_deletion_of_rows      CONSTANT param_type := 'Enable deletion of rows';
  c_enable_generic_change_log    CONSTANT param_type := 'Enable generic change log';
  c_sequence_name                CONSTANT param_type := 'Sequence name (example: #TABLE_NAME#_SEQ)';
```

``` sql
  FUNCTION get_params RETURN t_param IS
    v_params t_param;
  BEGIN
    v_params(c_unchange_existing_api_params) := 'True';
    v_params(c_col_prefix_in_method_names) := 'True';
    v_params(c_enable_deletion_of_rows) := 'False';
    v_params(c_enable_generic_change_log) := 'False';
    v_params(c_sequence_name) := NULL;
    RETURN v_params;
  END get_params;
```

``` sql
  FUNCTION get_ordered_params RETURN t_string IS
  BEGIN
    RETURN NEW t_string(c_unchange_existing_api_params,
                        c_col_prefix_in_method_names,
                        c_enable_deletion_of_rows,
                        c_enable_generic_change_log,
                        c_sequence_name);

  END get_ordered_params;
```

I get this order in the interface:
- Unchange existing API package parameters
- Enable generic change log
- Enable deletion of rows
- Sequence name (example: #TABLE_NAME#_SEQ)
- Keep column prefix in method names

![image](https://cloud.githubusercontent.com/assets/10425445/16117824/4bf60168-33d4-11e6-9110-e6e1bfa4eaa8.png)

Do you have any hint, how I can workaround my order and visibility problems? At least the sort order for my generator is important. I can't see any logic in the current sort order - also not, when I change the param names.

Thanks and kind regards
Ottmar

**Comment by PhilippSalvisberg** [comment]
Hello Ottmar,

Thank you for your feedback. 

You are probably referring to my blog post [How to Integrate Your PL/SQL Generators in SQL Developer](https://www.salvis.com/blog/2016/05/22/how-to-integrate-your-plsql-generators-in-sql-developer/). And you are right, `get_ordered_params` and `refresh_param_states` do not work with version 0.1.1, but they will work with version 0.2.0 which will be released this week, see also issue #7, #8 and #13 . 

You may download the current snapshot version [here](https://oss.sonatype.org/content/repositories/snapshots/org/oddgen/sqldev/0.2.0-SNAPSHOT/sqldev-0.2.0-20160616.141534-2.zip). Install this version and you're generator should show the parameters in the right order.

HTH.

Cheers,
Philipp

**Comment by ogobrecht** [comment]
Hi Philipp,

thank you for your quick answer. Since you plan to release the version 0.2 this week, I will simply wait  and try it out next week :-)

Have a nice weekend,
Ottmar

**Comment by PhilippSalvisberg** [comment]
Hello Ottmar,

That's fine. 

Enjoy the weekend end the Euro 2016,
Philipp
