### ISSUE TITLE
Extend generator interfaces to support custom navigator trees

### ISSUE THREAD

**Issue by PhilippSalvisberg** [oddgen/oddgen#28]
Currently the navigator tree is build on the following levels:
1. Generator Type (client or database server)
2. Generator Name
3. Object Type
4. Object Name

As explained in issue #10 and #26 this is not enough. A way to solve all these issues is to extend the generator interface to override the default behaviour by providing some kind of schema for the tree structure (details to be elaborated).

Solving this issue properly would implicitly solve issue #10 and #26 and similar other ones.

**Comment by MikeKutz** [comment]
Suggestion -
Similar to WebDAV, you will need a call that can be recursive.

I suggest something like this:

``` sql
type t_dir_object is record (
        display_order int, -- display order
    type varchar2(1),  -- D = Directory, O = Object
    icon varchar2(32), -- TABLE, FOLDER, etc...
    name varchar2(32), -- value listed in tree
    description varchar2( 32767 ), -- tooltip, etc.
);
type t_dir_listing is table of t_dir_object;
function tree_list( p_path in varchar2, p_depth in varchar2 := 0 ) return t_dir_listing;
```

MK

**Comment by mortenbra** [comment]
How about a function that returns a cursor with the treeview data, such as 

function get_treeview_data return sys_refcursor;

Inside the function the developer would open and return a cursor that selects the id, level, parent_id, name, description, type (folder or object), object_type, etc. to populate the treeview.

My requirement in #26 could then be solved by returning a "folder" for each package, and each subprogram within the package as an object of object type FUNCTION or PROCEDURE. As long as the oddgen plugin passes back the contextual info (including the level and the parent_id) to the generate() procedure, I should be able to figure out what the user has selected.

**Comment by PhilippSalvisberg** [comment]
Returning a sys_refcursor means that the returning structure has to be based on a query. This is too restrictive from my point of view. At least a part of the tree structure might come from somewhere else, especially when I think about client generators.

With the approach Mike suggested the tree will be populated lazily. Opening a folder node leads to a call. This is simple and most probably fast enough. However, a similar option to the sys_refcursor variant could be to return the complete tree structure. This could be a nested or a flat structure. Examples are:
- [jsTree](https://www.jstree.com/docs/json/) supports two JSON formats to populate their trees
- [Google chart](https://developers.google.com/chart/interactive/docs/gallery/treemap) uses a flat structure for their tree maps.

Right now I favour of Mike's approach because it supports the lazy loading concept of the used class [DefaultContainer](http://docs.oracle.com/middleware/1213/jdev/api-reference-esdk/oracle/ide/model/DefaultContainer.html) in SQL Developer. Since we never do an expand-all, lazy-loading seems to be the way to go in this case.

I'd like to configure the following properties per node/folder node:
- Parameters (parameter values set by this node, usually its just on per level, includes object_type and object_name as well - these parameters will be disabled in the generate dialog)
- Name (as suggested by Mike)
- Description (as suggested by Mike)
- Selectable (allows to select a folder with all its children for generation)
- MayBeParticipatorOfMultiSelection (horrible name, but you get the idea)
- IconName (reference to an existing icon as suggested by Mike)
- IconBase64 (Base64 encoded icon, see [Online Converter](https://www.base64-image.de/))

The order of the nodes should be preserved.

**Comment by mortenbra** [comment]
"Returning a sys_refcursor means that the returning structure has to be based on a query." -> That's actually a good thing in my opinion! :-) It gives the developer the full power of SQL, from a simple query to a very complex one. But I agree the disadvantage is that the whole tree has to be returned with one call, instead of lazily loaded. Perhaps you could aim to support both approaches! :-)

**Comment by PhilippSalvisberg** [comment]
> Perhaps you could aim to support both approaches! :-)

Do you mean returning a sys_ref_cursor? - I agree on using SQL to query data from the database, but when the data is not there, to force a returning structure to be a SQL is IMHO not a good thing. So, I'm not convinced ;-)

**Comment by mortenbra** [comment]
Any progress on this enhancement?

**Comment by PhilippSalvisberg** [comment]
I've defined the interface v0.3 some months ago here: https://github.com/oddgen/oddgen/blob/issue_28/sqldev/src/main/resources/org/oddgen/sqldev/resources/oddgen_interface.pks - feedback is appreciated. Should find time to implement it soon.

**Comment by MikeKutz** [comment]
If the `ID` and `PARENT_ID` were to use names instead of numerical PK/FK values, I'd relate the size of `key_type` to that of an Oracle Object Name. eg
`SUBTYPE key_type SYS.USER_OBJECTS.OBJECT_NAME%TYPE;`

But, I prefer to use CHAR instead of BYTE, and, not everyone is using 12.2c.
`TYPE key_type VARCHAR2(128 CHAR);`

I have 2 other ideas, but they might be better off as Enhancement Requests.

MK

**Comment by PhilippSalvisberg** [comment]
Good idea to use 128 bytes instead of 100  for ```key_type``` to support the new identifier length in Oracle Database 12.2. I'll change that. However, I prefer CHAR semantic over BYTE, since we in Europe deal with multi-byte characters sets quite often and it is supported in Oracle Database 9.2 as well (oldest version we are going to support).

**Comment by PhilippSalvisberg** [comment]
branch issue_28 rebased with master branch. New interfaces for PL/SQL and Java are finalised for v0.3.0.
