### ISSUE TITLE
No connection combo box is visible in the "Generators" window

### ISSUE THREAD

**Issue by mortenbra** [oddgen/oddgen#29]
Installed Oddgen 0.2.2 in SQL Developer 4.0.1 using the "Update Center". After restarting SQL Developer and selecting View, Generators, the "Generators" window appears, but there is no connection combo box to select a connection from.

![capture](https://cloud.githubusercontent.com/assets/9341579/16300397/16503d1e-3940-11e6-95e8-7e5a445b9ee7.JPG)

**Comment by PhilippSalvisberg** [comment]
Hmm, I'll have look later, which OS are you using?

**Comment by mortenbra** [comment]
Windows 8.1 (64-bit)

Java(TM) Platform   1.7.0_51
Oracle IDE  4.0.1.14.48
Versioning Support  4.0.1.14.48

**Comment by PhilippSalvisberg** [comment]
Thx, and the installation directory of sql developer?

**Comment by mortenbra** [comment]
"C:\Program Files\oracle_sqldeveloper\sqldeveloper401\sqldeveloper\bin\sqldeveloper64W.exe"

**Comment by PhilippSalvisberg** [comment]
Have you started SQL Developer als Administrator? - Installation of extension won't succeed otherwise, a problem with any extension on Windows. See also https://www.oddgen.org/download#faq (number 2 - I cannot install any extension on Windows).

Meanwhile I'm downloading 4.0.1 (slow mobile internet connection) and try to reproduce it. - So far it is working with 4.0.3 and 4.1.3 installed in a dedicated user directory (C:\app) on Windows 10.

**Comment by mortenbra** [comment]
The first time I installed, I didn't run run SQL Developer as administrator (although my user account has local admin privs). I didn't get any error messages during installation and everything appeared OK except for the missing connection combo box.

I now tried removing the extension, restarted SQL Developer using "Run as administrator", installed the extension again (once again there were no error messages). Restarted SQL Developer after installation, then restarted again with "run as administrator" just for good measure, but the result is the same: There is no connection combo box visible.

**Comment by PhilippSalvisberg** [comment]
Strange that it is not working when you use "Run as Adminstrator". If you do not have local admin rights, there is no way to install extensions when SQL Developer is installed in C:\Program Files. The only option is to install it in a user directory. But since you have local admin rights, it should work... 

...I come back as soon as I've completed my tests with the 4.0.1.

**Comment by PhilippSalvisberg** [comment]
### Findings
- Fixing issue #4 lead to incompatibility with older SQL Developer 4.0 releases.
- oddgen for SQL Developer v0.2.x requires SQL Developer 4.0.2 or higher
- Client Generators cannot be recognized in SQLDEV_HOME with a space in the directory, new issue #31 created

### Notes to Reproduce

#### Backup
- Started the existing 4.1.3 SQL Developer and exported my connections.
- Windows 10 VM Snapshot...

#### Run 4.0.1 as Normal User
- Deleted folders
  - C:\Users\phs\AppData\Roaming\SQL Developer
  - C:\Users\phs\AppData\Roaming\sqldeveloper
- Unzipped sqldeveloper-4.0.1.14.48-x64.zip
- Copied the sqldeveloper folder to C:\Program Files
- Started sqldeveloper.exe as normal user
- Imported connections.
- Installed oddgen for SQL Developer 0.2.2 via Update Center
- Doing a "restart now"
- Got no error message
- "Generators" under "View" is not visible
- Tools->Features->Installed Updates does not show any installed extensions

#### Run 4.0.1 as Admin User
- Exited SQL Developer
- Right click on sqldeveloper.exe and selected "Run as administrator"
- Installed oddgen for SQL Developer 0.2.2 via Update Center
- Doing a "restart now"
- Selected View->Generators
- Generator Window showed up, BUT toolbar is missing!
- Closed Generator Window
- Selected View->Generators
- Window does not show up
- No entries in Logging window

#### Run 4.0.1 with Logging as Admin
- Exited SQL Developer
- Opened logging.conf
- Replaced 

existing content 

```
.level=SEVERE

# Set the default logging level for the root logger
#oracle.level = INFO

# --- ConsoleHandler ---
# Override of global logging level
java.util.logging.ConsoleHandler.level=ALL
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
oracle.dbtools.logging.LogPaneHandler.level=ALL
oracle.ide.log.QueuedLoggingHandler.level=OFF
```

with

```
#handler for console only (will be shown in Messages pane within SQL Developer)
handlers=java.util.logging.ConsoleHandler

# Default global logging level. 
.level=SEVERE

# Loggers 
oracle.level=FINE
org.oddgen.level=FINE

# --- ConsoleHandler --- 
java.util.logging.ConsoleHandler.level=FINE
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
java.util.logging.SimpleFormatter.format=%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS %4$s %3$s: %5$s%n

```
- Started sqldeveloper.exe as administrator
- Analyzed log file and found the following relevant entry
- Selected View->Generators showed up without toolbar
- Selected View->Log and analsed the content. The following line was interesting:

```
2016-06-23 16:32:58 FINE org.oddgen.sqldev.OddgenNavigatorWindow: #createToolbar(): thrown java.lang.NoClassDefFoundError(oracle/dbtools/worksheet/editor/ConnComboBox) out of org.oddgen.sqldev.OddgenNavigatorWindow#createToolbar_aroundBody0[108] in 1ms
```

#### Run 4.0.3 as Admin
- Copied the sqldeveloper folder to C:\Program Files
- Started sqldeveloper.exe as administrator
- Imported preferences from previous installation (asked by SQL Developer)
- Selected View->Generators
- Generators window showed up including the toolbar.
- No additional installation was necessary.

#### Run 4.0.3 as Normal User
- Exited SQL Developer
- Started sqldeveloper.exe as normal user
- Connected to user scott.
- Client Generators are not shown.
- The following log entry was interesting:

```
2016-06-23 17:07:33 INFO org.oddgen.sqldev.GeneratorFolderNode: #openBackground(): thrown java.net.URISyntaxException(Illegal character in path at index 16: file:/C:/Program Files/sqldeveloper/sqldeveloper/extensions/org.oddgen.sqldev.jar) out of java.net.URI$Parser#fail[2829] in 1s
```

#### Run 4.0.2 as Admin
- Restore to previous Windows VM 10 snapshot
- Deleted folders
  - C:\Users\phs\AppData\Roaming\SQL Developer
  - C:\Users\phs\AppData\Roaming\sqldeveloper
- Unzipped sqldeveloper-4.0.2.15.21-x64
- Copied the sqldeveloper folder to C:\Program Files
- Started sqldeveloper.exe as normal user
- Imported connections.
- Exited SQL Developer
- Started sqldeveloper.exe as administrator
- Installed oddgen for SQL Developer 0.2.2 via Update Center
- Doing a "restart now"
- Selected View->Generators
- Generator Window showed up, including toolbar!

#### Restore
- Restore to previous Windows VM 10

**Comment by PhilippSalvisberg** [comment]
changed prerequisites in release notes for v0.1.0 and v0.2.0. - New connection handling requires SQL Developer 4.0.2. I do not plan to fix this bug. Please update to a newer version of SQL Developer.

**Comment by mortenbra** [comment]
Just to confirm, I upgraded to SQL Developer 4.0.3, and this now works as expected.

**Comment by PhilippSalvisberg** [comment]
Thanks for letting me know :-)
