### ISSUE TITLE
Show "connect to DB window" when oddgen is not connected to a DB

### ISSUE THREAD

**Issue by MikeKutz** [oddgen/oddgen#4]
Enhancement request:
Initial start of SQL*Developer shows oddgen plugin like this:
![image](https://cloud.githubusercontent.com/assets/14933751/13847702/cbbf76a6-ec24-11e5-9430-dac1e402bb2b.png)

If a DB is not selected or a DB is selected but not connected, the "connect to DB" window should pop-up when the "refresh" button is clicked

Also, This window should appear when a non-connected DB is selected for oddgen.
ie
![image](https://cloud.githubusercontent.com/assets/14933751/13847879/c34cdddc-ec25-11e5-9fad-7df73561ac9b.png)

**Comment by PhilippSalvisberg** [comment]
I agree. The connection is opened only if the password has been saved for the connection. The goal is to mimic the behaviour of the connection combobox in a worksheet.
