### ISSUE TITLE
No Database Server Generators shown if error raised on one

### ISSUE THREAD

**Issue by jeffreykemp** [oddgen/oddgen#41]
All of a sudden all my Database Server Generators disappeared from the list. I've checked the Log which indicated one of my packages "get_name" was raising an exception.

Can oddgen be made more resilient so that it skips over (or better, reports problems with) bad generator packages?

**Comment by PhilippSalvisberg** [comment]
Agreed. This is bad. It should be possible to 

1. Fall back to default behaviour if the call to ```get_name```, ```get_description```, etc. raises an exception.
2. Report the exception either in a dedicated pseudo node or as part of the generator description, which is shown in various places. I'm in favour of the extended description. It's consistent with the solution for runtime errors in the ```generate```function, simple to implement and visible in the tree via mouse-over, in the status bar (at least a part) and when opening the generate dialog.

Here are the steps to reproduce the issue:

### 1. Create bad generator
```
CREATE OR REPLACE PACKAGE issue41 IS
   FUNCTION get_name RETURN VARCHAR2;

   FUNCTION generate (
      in_object_type IN VARCHAR2,
      in_object_name IN VARCHAR2
   ) RETURN CLOB;
END issue41;
/

CREATE OR REPLACE PACKAGE BODY issue41 IS
   FUNCTION get_name RETURN VARCHAR2 IS
      l_name VARCHAR2(100) := 'Issue41';
   BEGIN
      EXECUTE IMMEDIATE 'runtime error in get_name' INTO l_name;
      RETURN l_name;
   END get_name;

   FUNCTION generate (
      in_object_type IN VARCHAR2, 
      in_object_name IN VARCHAR2
   ) RETURN CLOB IS
      l_result CLOB;
   BEGIN
      EXECUTE IMMEDIATE 'runtime error in generate' INTO l_result;
      RETURN l_result;
   END generate;
END issue41;
/
```

### 2. Refresh Generators

Leads to a an empty "Generators" node

![oddgen_issue41](https://cloud.githubusercontent.com/assets/3883171/21834878/d80fbc42-d7b8-11e6-830d-87dde6759a2a.png)

### 3. Fix get_name

```
CREATE OR REPLACE PACKAGE BODY issue41 IS
   FUNCTION get_name RETURN VARCHAR2 IS
      l_name VARCHAR2(100) := 'Issue41';
   BEGIN
      -- EXECUTE IMMEDIATE 'runtime error in get_name' INTO l_name;
      RETURN l_name;
   END get_name;

   FUNCTION generate (
      in_object_type IN VARCHAR2, 
      in_object_name IN VARCHAR2
   ) RETURN CLOB IS
      l_result CLOB;
   BEGIN
      EXECUTE IMMEDIATE 'runtime error in generate' INTO l_result;
      RETURN l_result;
   END generate;
END issue41;
/
```

### 4. Refresh Generators again

Generators node looks good.

![oddgen_issue41_2](https://cloud.githubusercontent.com/assets/3883171/21835069/6c41d2c8-d7ba-11e6-81be-338b211853a5.png)

### 5. Generate

Exceptions are catched and returned as generator result:

```
Failed to generate code for TABLE.DEPT via OGDEMO.ISSUE41. Got the following error: ORA-00900: invalid SQL statement
ORA-06512: at "OGDEMO.ISSUE41", line 15
ORA-06512: at line 4
```
