### ISSUE TITLE
Remove "Hello World" Client Generator from download

### ISSUE THREAD

**Issue by SvenWeller** [oddgen/oddgen#44]
How can I get rid of the "Hello World" Client generator? Please provide a "clean oddgen" version. Hello World is good for testing purposes. But when I'm using SQL Developer in a professional environment then I want to see only the generators I actively use.

**Comment by MikeKutz** [comment]
I would imagine that modifying the "preferences" would do the trick.
I had to remove the client-side 12c ones because I'm running things on XE.

![image](https://user-images.githubusercontent.com/14933751/26841497-b031dff8-4ab7-11e7-8f6a-0ae3342bc9b1.png)

**Comment by PhilippSalvisberg** [comment]
Mike is correct. Uncheck "Client generator examples" and the generators "Hello world" and "1:1 View" will not be shown. 

I've disabled these generators in my SQL Developer installation as well. See the following screenshot.

![generators](https://user-images.githubusercontent.com/3883171/26844578-2a8c699e-4af4-11e7-850a-99b0f963c7eb.png)

**Comment by SvenWeller** [comment]
Perfect, Thanks Mike!
