### ISSUE TITLE
improvemnts for oddgen_types.pks comments

### ISSUE THREAD

**Issue by MikeKutz** [oddgen/oddgen#52]
I was reading the code for `oddgen_types.pks` but still have some questions about the usage of the data types.

File reference:
https://github.com/oddgen/oddgen/blob/master/examples/package/oddgen_types.pks

1. What MIME Types are supported for `r_node_type.icon_base64`?
2. The comment for `r_node_type.generatable` states a default value ( `leaf` ) which is invalid for the data type ( `BOOLEAN` ).  What is the actual default value?
3. I have the same question for `multiselectable` and `relevant`.

Thanks

MK

**Comment by PhilippSalvisberg** [comment]
> 1. What MIME Types are supported for ```r_node_type.icon_base64```?

Good question. I have tested with png only, have to check what the supported icons for SQL Developer are. To convert to a png to base64 I've used https://www.base64-image.de/ . just make sure to remove the "data:image/png;base64," prefix.

The example in https://github.com/oddgen/oddgen/blob/master/examples/package/plsql/emp_hier.pkb uses a Base64 encoded icon.

> 2. The comment for ```r_node_type.generatable``` states a default value ( leaf ) which is invalid for the data type ( BOOLEAN ). What is the actual default value?

it is actually the value of leaf, if generatable is NULL. 

> 3. I have the same question for ```multiselectable``` and relevant.

Answer is the same as for 2.

**Comment by MikeKutz** [comment]
I would imagine that you could use any MIME Type that Eclipse supports. (which should be most of the well known ones)

For 2 and 3 -- Ahh... the "default value" is value of `r_node_type.leaf`

Thanks,

MK

**Comment by PhilippSalvisberg** [comment]
I've checked it. Behind the scenes an ImageIcon is used which supports the GIF, JPEG and PNG format.
