### ISSUE TITLE
View --> Generators not working with SQL Developer 19.1

### ISSUE THREAD

**Issue by felwehedi** [oddgen/oddgen#53]
I just upgraded to 19.1 and everytime i try to open Generators view it just doesn't show up. I have enabled logging in SQL Developer and the only thing i see is:
com.jcabi.log.Logger | OddgenNavigatorWindow shown

Which shows no errors in the logs but still the  Window doesn't show.

**Comment by PhilippSalvisberg** [comment]
The extensions should work in 19.1. In fact I've tested it successfully on macOS and Windows.

I suspect an issue with SQL Developer's system cache. I suggest to try one of the following:

a) Reset Windows To Factory Settings

![image](https://user-images.githubusercontent.com/3883171/56116428-0cf20000-5f66-11e9-9aaf-5ab6a557c993.png)

b) Delete the `system_cache` folder

1. Close SQL Developer
2. Open a terminal window and execute
    * on macOS `rm -rf $HOME/.sqldeveloper/system19.1.0.094.2042/system_cache`
    * on Windows `rmdir /s /q "%APPDATA%\SQL Developer\system19.1.0.094.2042\system_cache"`
3. Restart SQL Developer

Please let me know if this solved the issue.

**Comment by felwehedi** [comment]
Yep that resolved the issue. Thank you very much
