### ISSUE TITLE
Can't show PACKAGE icon in SQLDeveloper 20.2

### ISSUE THREAD

**Issue by MikeKutz** [oddgen/oddgen#55]
I don't remember if "other icons" were implemented. (see #14)

But, I can't seem to change the icon based on the icon_name value.

- SQLDeveloper -  v20.2
- Database - ATP Free Tier (v19.5) (Oracle Cloud - Autonomous Transaction Processor - Free Tier)
- Client OS - Windows 7 Home (64bit)

![image](https://user-images.githubusercontent.com/14933751/92326228-a2d87000-f01e-11ea-9dab-a7ad7ff4ec96.png)

CODE
===
```sql
CREATE OR REPLACE PACKAGE test_icons AS
  FUNCTION generate( node IN oddgen_types.r_node_type )
    RETURN CLOB;

  FUNCTION get_nodes( in_parent_node_id IN oddgen_types.key_type DEFAULT NULL )
    RETURN oddgen_types.t_node_type;
    
  function get_name return varchar2;

END;
/

CREATE OR REPLACE PACKAGE body test_icons AS
  FUNCTION generate( node IN oddgen_types.r_node_type )
    RETURN CLOB
  as
  begin
    return 'hello world.';
  end;

  FUNCTION get_nodes( in_parent_node_id IN oddgen_types.key_type DEFAULT NULL )
    RETURN oddgen_types.t_node_type
  as
      a_node oddgen_types.r_node_type;
      b_node  oddgen_types.r_node_type;
     begin
     
        a_node.name            := 'Package Icon';
        a_node.icon_name       := 'PACKAGE';
        a_node.leaf            := true;
        a_node.generatable     := true;

        b_node.name            := 'View Icon';
        b_node.icon_name       := 'VIEW';
        b_node.leaf            := true;
        b_node.generatable     := true;

        RETURN oddgen_types.t_node_type(  a_node, b_node );
  
  end;
  
  function get_name return varchar2
  as
  begin
    return 'Test Icons';
  end;

END;
/
```

**Comment by PhilippSalvisberg** [comment]
The `a_node.icon_name` and the `b_node.icon_name` do not exists. Therefore the default icon (unknown) is used. 

I guess you wanted to use `PACKAGE_ICON` and `VIEW_ICON`. I changed your code and the result was:

![image](https://user-images.githubusercontent.com/3883171/92330127-d510be80-f06c-11ea-9250-afcdc1ac1100.png)

See the first section in [OddgenResources.properties](https://github.com/oddgen/oddgen/blob/main/sqldev/src/main/resources/org/oddgen/sqldev/resources/OddgenResources.properties) for a list of all icons that can be defined by name. However, you can always provide a PNG in Base64 format.

HTH

**Comment by MikeKutz** [comment]
That's what I thought.  I had the values for `icon_name` wrong.

I was looking for a list of valid values in the documentation at https://www.oddgen.org/plsql-interface/ but didn't see any.

The documentation also seems to be missing information on `t_node_type`.  Although its easy to figure out (by naming convention), it would make sense (for be thoroughness) to include it on the Documentation page.

Again, thanks for the help.

My $0.02

MK

**Comment by PhilippSalvisberg** [comment]
Yes, there could be always more documentation. However, when reading the documentation in `oddgen_types` one should get the pattern. And `VIEW_ICON` is documented. Did not help... ;-)
