### ISSUE TITLE
Code not generated in specific order?

### ISSUE THREAD

**Issue by MikeKutz** [oddgen/oddgen#58]
When I select multiple templates and do bulk code generation, the order of the generated files does not seem to be generated in a specific order.

The set of templates I generate have dependencies.  They need to be ran in a specific order.  It would be nice if I could R-Click on the folder and "generate all" (this works) and the generated code is in the same order as it is displayed (this does not seem to work) so I can just click Run Script (F5) and "it works".

I got the order-of-display to work
![image](https://user-images.githubusercontent.com/14933751/93018525-57820c80-f59e-11ea-89a8-0e67a9318f91.png)

But the order of code generation seems mixed up. (LB_APEX_API is generated first and LB_API is generated last).

Am I doing something wrong or is the a "feature request"?

**update** it seems only LB_APEX_API and LB_API are generated.  Selecting a single package to generate works (for all packages).

SQLDeveloper v20.2
DB 19.5c (ATP Free Tier)

**Comment by PhilippSalvisberg** [comment]
>When I select multiple templates and do bulk code generation, the order of the generated files does not seem to be generated in a specific order.

The order is typically based on the order of the nodes in the GUI, e.g. when you call the generator based on `Individual Packages` the nodes are sorted as in the tree. When you select them individually the nodes are sorted in the order you select them.

>It seems only LB_APEX_API and LB_API are generated

This seems to be an issue with your generator. I cannot reproduce it.

**Comment by PhilippSalvisberg** [comment]
@MikeKutz have you solved the issue with your generator?

BTW you can control the sort order in the generator yourself. When you generate basically all the code in the `generate_prolog` or `generate_epilog` function. See https://github.com/oddgen/oddgen/blob/main/examples/package/plsql/dropall.pkb#L267-L290 where the nodes are sorted using SQL to generate drop statements in the "right" order.

**Comment by MikeKutz** [comment]
@PhilippSalvisberg - I have not had a chance to look at this issue (in more detail) yet.

I've been working on some enhancements for the tePLSQL engine.  One enhancement would require a rework of my generator to use the `generate_prolog` function like you have suggested.

Before I do that, I'll try creating a few test cases for you.

**Comment by MikeKutz** [comment]
Here is a test package and a "`get_nodes` returns correctly?" anonymous block.

If I double click of folder `File Set A`, I only get 2x nodes generated.

![image](https://user-images.githubusercontent.com/14933751/95664259-fead8180-0b13-11eb-99a2-62eb1e0f7733.png)


```sql
create or replace
package oddgen_test_pkg
  authid current_user
as
    function generate( in_node in oddgen_types.r_node_type )
      return clob;
      
      function get_name return varchar2;

    FUNCTION get_nodes(
        in_parent_node_id IN oddgen_types.key_type DEFAULT NULL
     ) RETURN oddgen_types.t_node_type;
end;
/

create or replace
package body oddgen_test_pkg
as
    function generate( in_node in oddgen_types.r_node_type )
      return clob
    as
    begin
      return to_char(sysdate, 'yyyy-mm-dd hh24:mi:ss') || ' - Generating something for "' || in_node.name || '"';
    end;
    
    FUNCTION get_nodes(
        in_parent_node_id IN oddgen_types.key_type DEFAULT NULL
     ) RETURN oddgen_types.t_node_type
     as
      return_value oddgen_types.t_node_type;
      
      a_node oddgen_types.r_node_type;
      b_node oddgen_types.r_node_type;
      c_node oddgen_types.r_node_type;
      d_node oddgen_types.r_node_type;
      u1_node oddgen_types.r_node_type;
      u2_node oddgen_types.r_node_type;
      
      
      a_folder oddgen_types.r_node_type;
      b_folder oddgen_types.r_node_type;
     begin
        a_folder.id              := 'Folder_A';
        a_folder.name            := 'File Set A';
        a_folder.leaf            := false;
        a_folder.generatable     := true;
        a_folder.multiselectable := false;  
     
        a_node.id              := 'Node_A';
        a_node.parent_id       := 'Folder_A';
        a_node.name            := 'Node A';
        a_node.icon_name       := 'PACKAGE_ICON';
        a_node.leaf            := true;
        a_node.generatable     := true;
        a_node.multiselectable := true;  

        b_node.name            := 'Node_B';
        b_node.parent_id       := 'Folder_A';
        b_node.name            := 'Node B';
        b_node.icon_name       := 'PACKAGE_ICON';
        b_node.leaf            := true;
        b_node.generatable     := true;
        b_node.multiselectable := true;
        
        c_node.name            := 'Node_C';
        c_node.parent_id       := 'Folder_A';
        c_node.name            := 'Node C';
        c_node.icon_name       := 'PACKAGE_ICON';
        c_node.leaf            := true;
        c_node.generatable     := true;
        c_node.multiselectable := true;
        
        d_node.name            := 'Node_D';
        d_node.parent_id       := 'Folder_A';
        d_node.name            := 'Node D';
        d_node.icon_name       := 'PACKAGE_ICON';
        d_node.leaf            := true;
        d_node.generatable     := true;
        d_node.multiselectable := true;

        b_folder.id              := 'Folder B';
        b_folder.name            := 'File Set B';
        b_folder.leaf            := false;
        b_folder.generatable     := true;
        b_folder.multiselectable := false;

        u1_node.name            := 'Node 91';
        u1_node.parent_id       := 'Folder B';
        u1_node.name            := 'Node 91';
        u1_node.icon_name       := 'PACKAGE_ICON';
        u1_node.leaf            := true;
        u1_node.generatable     := true;
        u1_node.multiselectable := true;

        u2_node.name            := 'Node 92';
        u2_node.parent_id       := 'Folder B';
        u2_node.name            := 'Node 92';
        u2_node.icon_name       := 'PACKAGE_ICON';
        u2_node.leaf            := true;
        u2_node.generatable     := true;
        u2_node.multiselectable := true;
        
    if in_parent_node_id is null
    then
      return oddgen_types.t_node_type( a_folder, b_folder );
    end if;
    
    case in_parent_node_id
      when a_folder.id then
        return_value := oddgen_types.t_node_type( c_node, b_node, a_node, d_node );
      when b_folder.id then
        return_value := oddgen_types.t_node_type(  u1_node, u2_node );
      else
        null;
    end case;
    
    return return_value;
  end;
    function get_name return varchar2
    as
    begin
      return 'Test for issue #58';
    end;
end;
/

set serveroutput on;
declare
  buf oddgen_types.t_node_type;
begin
  buf := oddgen_test_pkg.get_nodes( 'Folder_A' );
  for i in 1 .. buf.count
  loop
    dbms_output.put_line( 'i = ' || buf(i).name );
  end loop;
end;
```

**Comment by MikeKutz** [comment]
I feel stupid.

I just noticed I wasn't setting the `node.id` value.

case closed.
