### ISSUE TITLE
Possible change in operation (discussion)

### ISSUE THREAD

**Issue by MikeKutz** [oddgen/oddgen#9]
Currently, it looks like one will need to create 1 "generator" for each template.

Personally
- this is OK if you have only a few templates
- this is a horrible idea if you have a handful of templates
- this will be a nightmare when the API changes.  (you'd need a generator to regenerate all the generators)

The discussion/question:
Should the method to access templates be changed so that it is "1 generator that lists available templates"?

eg:
![oddgen list](https://cloud.githubusercontent.com/assets/14933751/13898335/4c4e637e-eda4-11e5-8e3e-d0bc9311bdc2.jpg)

**Comment by PhilippSalvisberg** [comment]
The oddgen SQLDev extension does not know about templates. It is not necessary. Templates are handled by generators. A generator may use internally several templates to accomplish its job. A generator may also validate the input or take responsibility to generate unique identifiers, something which cannot be done by templates. 

I understand that the current tree structure lacks user-defined grouping criteria and is not best suited to present hundreds of generators. But I do not see a major problem maintaining hundreds of generators in dedicated PL/SQL packages. Common code in the PL/SQL packages may be extracted into libraries and if you like to manage multiple templates in single PL/SQL package you may do that as well. But for each generator presented in the oddgen SQLDev extension you have to create a dedicated PL/SQL package at least as a wrapper to your generator and your templates. Each package defines just that what is needed:
- the generator (mandatory)
- a name (optional)
- a description (optional)
- the list of valid object types (optional)
- the list of valid object names (optional)
- the list of additional parameters (optional)
- the list of valid values for additional parameters (optional)
- the refreshed list of values for additional parameters based on current parameter values (optional)

So these are properties for a generator. I'd like to introduce the concept for templates to the SQLDev extension for client generators to enable users to adapt the template to their need. But for PL/SQL based generators the adaption could be done directly in the PL/SQL code.

However, I will open dedicated issue to address user-defined folders in the oddgen navigator tree.
